nodeLinker: hoisted

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.1
  vitest: 5.0.1

allowBuilds:
  electron-winstaller: true
  fsevents: true
  msw: true

peerDependencyRules:
  allowedVersions:
    vite: 1.0.0-rc.1
