export const TITLEBAR_HEIGHT = 48;

export const TITLEBAR_NAV_LEFT = 80;

const TITLEBAR_NAV_BUTTON = 28;
const TITLEBAR_NAV_BUTTON_GAP = 2;
const TITLEBAR_NAV_BUTTONS = 3;
const TITLEBAR_NAV_MARGIN = 24;

export const TITLEBAR_NAV_WIDTH =
  TITLEBAR_NAV_BUTTONS * TITLEBAR_NAV_BUTTON + (TITLEBAR_NAV_BUTTONS - 1) * TITLEBAR_NAV_BUTTON_GAP;

export const TITLEBAR_NAV_CLEARANCE = TITLEBAR_NAV_LEFT + TITLEBAR_NAV_WIDTH + TITLEBAR_NAV_MARGIN;

export const MAC_WINDOW_BUTTON_HEIGHT = 14;

export const MAC_WINDOW_BUTTON_POSITION = {
  x: 14,
  y: (TITLEBAR_HEIGHT - MAC_WINDOW_BUTTON_HEIGHT) / 2,
};
